CREATE TABLE USUARIOS (
id INTEGER PRIMARY KEY,
nombre TEXT NOT NULL,
apusuariosellido TEXT NOT NULL,
USUARIO TEXT NOT NULL,
CONTRASEÑA TEXT NOT NULL,
DOMICILIO TEXT NOT NULL,
BARRIO TEXT NOT NULL,
DIETA TEXT NOT NULL
)
  